data:
  path: "../JPL_Social/"
  sequence_length: 30

test:
  batch_size: 128

model:
  gcn_hidden_dim: 16
  gcn_num_layers: 3
  lstm_hidden_dim: 128
  lstm_num_layers: 3
  fc1_hidden: 64
  fc2_hidden: 16
